# Generated by Django 5.2.3 on 2025-06-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FS_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustable_parameters', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Справочник фильрующих методов отбора признаков',
                'verbose_name_plural': 'Справочник фильрующих методов отбора признаков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FS_Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustable_parameters', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Справочник методов-оберток отбора признаков',
                'verbose_name_plural': 'Справочник методов-оберток отбора признаков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ML_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustable_parameters', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Справочник моделей машинного обучения',
                'verbose_name_plural': 'Справочник моделей машинного обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('data_content', models.JSONField(blank=True, null=True)),
                ('target_variable', models.CharField(blank=True, max_length=255, null=True)),
                ('preliminarily_selected_features', models.JSONField(blank=True, null=True)),
                ('fs_filter_parameters', models.JSONField(blank=True, null=True)),
                ('fs_filter_selected_features', models.JSONField(blank=True, null=True)),
                ('fs_wrapper_parameters', models.JSONField(blank=True, null=True)),
                ('fs_wrapper_selected_features', models.JSONField(blank=True, null=True)),
                ('final_selected_features', models.JSONField(blank=True, null=True)),
                ('ml_model_parameters', models.JSONField(blank=True, null=True)),
                ('ml_model_metrics', models.JSONField(blank=True, null=True)),
                ('ml_model_shap_values', models.JSONField(blank=True, null=True)),
                ('fs_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='featurama.fs_filter')),
                ('fs_wrapper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='featurama.fs_wrapper')),
                ('ml_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='featurama.ml_model')),
            ],
            options={
                'verbose_name': 'Пайплайн',
                'verbose_name_plural': 'Пайплайны',
                'ordering': ['-id'],
            },
        ),
    ]
